
const Nationality_selectBox = () => {
  return (
      <select
        id="travelers.SKH-1-EXT.countryCode"
        data-testid="travelers.SKH-1-EXT.countryCode"
        name="travelers.SKH-1-EXT.countryCode"
        placeholder="Select nationality"
        required=""
        aria-activedescendant="US"
        aria-invalid="false"
        data-cy="Pax1-Nationality"
        className="tiketing_Line_selectBox" 
      >
        <option
          data-testid="travelers.SKH-1-EXT.countryCode-placeholder"
          disabled=""
          value=""
          aria-selected="false"
        >
          Select nationality
        </option>
        <optgroup label="">
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionIS"
            value="IS"
            aria-selected="false"
          >
            Iceland
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionNL"
            value="NL"
            aria-selected="false"
          >
            Netherlands
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionUS"
            value="US"
            aria-selected="true"
          >
            United States
          </option>
        </optgroup>
        <optgroup label=" ">
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAF"
            value="AF"
            aria-selected="false"
          >
            Afghanistan
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAX"
            value="AX"
            aria-selected="false"
          >
            Åland Islands
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAL"
            value="AL"
            aria-selected="false"
          >
            Albania
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionDZ"
            value="DZ"
            aria-selected="false"
          >
            Algeria
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAS"
            value="AS"
            aria-selected="false"
          >
            AmericanSamoa
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAD"
            value="AD"
            aria-selected="false"
          >
            Andorra
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAO"
            value="AO"
            aria-selected="false"
          >
            Angola
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAI"
            value="AI"
            aria-selected="false"
          >
            Anguilla
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAQ"
            value="AQ"
            aria-selected="false"
          >
            Antarctica
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAG"
            value="AG"
            aria-selected="false"
          >
            Antigua and Barbuda
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAR"
            value="AR"
            aria-selected="false"
          >
            Argentina
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAM"
            value="AM"
            aria-selected="false"
          >
            Armenia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAW"
            value="AW"
            aria-selected="false"
          >
            Aruba
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAU"
            value="AU"
            aria-selected="false"
          >
            Australia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAT"
            value="AT"
            aria-selected="false"
          >
            Austria
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAZ"
            value="AZ"
            aria-selected="false"
          >
            Azerbaijan
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBS"
            value="BS"
            aria-selected="false"
          >
            Bahamas
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBH"
            value="BH"
            aria-selected="false"
          >
            Bahrain
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBD"
            value="BD"
            aria-selected="false"
          >
            Bangladesh
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBB"
            value="BB"
            aria-selected="false"
          >
            Barbados
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBY"
            value="BY"
            aria-selected="false"
          >
            Belarus
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBE"
            value="BE"
            aria-selected="false"
          >
            Belgium
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBZ"
            value="BZ"
            aria-selected="false"
          >
            Belize
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBJ"
            value="BJ"
            aria-selected="false"
          >
            Benin
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBM"
            value="BM"
            aria-selected="false"
          >
            Bermuda
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBT"
            value="BT"
            aria-selected="false"
          >
            Bhutan
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBO"
            value="BO"
            aria-selected="false"
          >
            Bolivia, Plurinational State of
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBA"
            value="BA"
            aria-selected="false"
          >
            Bosnia and Herzegovina
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBW"
            value="BW"
            aria-selected="false"
          >
            Botswana
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBR"
            value="BR"
            aria-selected="false"
          >
            Brazil
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionIO"
            value="IO"
            aria-selected="false"
          >
            British Indian Ocean Territory
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBN"
            value="BN"
            aria-selected="false"
          >
            Brunei Darussalam
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBG"
            value="BG"
            aria-selected="false"
          >
            Bulgaria
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBF"
            value="BF"
            aria-selected="false"
          >
            Burkina Faso
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBI"
            value="BI"
            aria-selected="false"
          >
            Burundi
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionKH"
            value="KH"
            aria-selected="false"
          >
            Cambodia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCM"
            value="CM"
            aria-selected="false"
          >
            Cameroon
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCA"
            value="CA"
            aria-selected="false"
          >
            Canada
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCV"
            value="CV"
            aria-selected="false"
          >
            Cape Verde
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionKY"
            value="KY"
            aria-selected="false"
          >
            Cayman Islands
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCF"
            value="CF"
            aria-selected="false"
          >
            Central African Republic
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTD"
            value="TD"
            aria-selected="false"
          >
            Chad
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCL"
            value="CL"
            aria-selected="false"
          >
            Chile
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCN"
            value="CN"
            aria-selected="false"
          >
            China
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCX"
            value="CX"
            aria-selected="false"
          >
            Christmas Island
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCC"
            value="CC"
            aria-selected="false"
          >
            Cocos (Keeling) Islands
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCO"
            value="CO"
            aria-selected="false"
          >
            Colombia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionKM"
            value="KM"
            aria-selected="false"
          >
            Comoros
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCG"
            value="CG"
            aria-selected="false"
          >
            Congo
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCD"
            value="CD"
            aria-selected="false"
          >
            Congo, The Democratic Republic of the
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCK"
            value="CK"
            aria-selected="false"
          >
            Cook Islands
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCR"
            value="CR"
            aria-selected="false"
          >
            Costa Rica
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCI"
            value="CI"
            aria-selected="false"
          >
            Cote d'Ivoire
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionHR"
            value="HR"
            aria-selected="false"
          >
            Croatia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCU"
            value="CU"
            aria-selected="false"
          >
            Cuba
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCY"
            value="CY"
            aria-selected="false"
          >
            Cyprus
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCZ"
            value="CZ"
            aria-selected="false"
          >
            Czech Republic
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionDK"
            value="DK"
            aria-selected="false"
          >
            Denmark
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionDJ"
            value="DJ"
            aria-selected="false"
          >
            Djibouti
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionDM"
            value="DM"
            aria-selected="false"
          >
            Dominica
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionDO"
            value="DO"
            aria-selected="false"
          >
            Dominican Republic
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionEC"
            value="EC"
            aria-selected="false"
          >
            Ecuador
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionEG"
            value="EG"
            aria-selected="false"
          >
            Egypt
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSV"
            value="SV"
            aria-selected="false"
          >
            El Salvador
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGQ"
            value="GQ"
            aria-selected="false"
          >
            Equatorial Guinea
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionER"
            value="ER"
            aria-selected="false"
          >
            Eritrea
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionEE"
            value="EE"
            aria-selected="false"
          >
            Estonia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionET"
            value="ET"
            aria-selected="false"
          >
            Ethiopia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionFK"
            value="FK"
            aria-selected="false"
          >
            Falkland Islands (Malvinas)
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionFO"
            value="FO"
            aria-selected="false"
          >
            Faroe Islands
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionFJ"
            value="FJ"
            aria-selected="false"
          >
            Fiji
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionFI"
            value="FI"
            aria-selected="false"
          >
            Finland
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionFR"
            value="FR"
            aria-selected="false"
          >
            France
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGF"
            value="GF"
            aria-selected="false"
          >
            French Guiana
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPF"
            value="PF"
            aria-selected="false"
          >
            French Polynesia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGA"
            value="GA"
            aria-selected="false"
          >
            Gabon
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGM"
            value="GM"
            aria-selected="false"
          >
            Gambia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGE"
            value="GE"
            aria-selected="false"
          >
            Georgia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionDE"
            value="DE"
            aria-selected="false"
          >
            Germany
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGH"
            value="GH"
            aria-selected="false"
          >
            Ghana
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGI"
            value="GI"
            aria-selected="false"
          >
            Gibraltar
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGR"
            value="GR"
            aria-selected="false"
          >
            Greece
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGL"
            value="GL"
            aria-selected="false"
          >
            Greenland
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGD"
            value="GD"
            aria-selected="false"
          >
            Grenada
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGP"
            value="GP"
            aria-selected="false"
          >
            Guadeloupe
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGU"
            value="GU"
            aria-selected="false"
          >
            Guam
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGT"
            value="GT"
            aria-selected="false"
          >
            Guatemala
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGG"
            value="GG"
            aria-selected="false"
          >
            Guernsey
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGN"
            value="GN"
            aria-selected="false"
          >
            Guinea
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGW"
            value="GW"
            aria-selected="false"
          >
            Guinea-Bissau
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGY"
            value="GY"
            aria-selected="false"
          >
            Guyana
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionHT"
            value="HT"
            aria-selected="false"
          >
            Haiti
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionVA"
            value="VA"
            aria-selected="false"
          >
            Holy See (Vatican City State)
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionHN"
            value="HN"
            aria-selected="false"
          >
            Honduras
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionHK"
            value="HK"
            aria-selected="false"
          >
            Hong Kong
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionHU"
            value="HU"
            aria-selected="false"
          >
            Hungary
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionIS"
            value="IS"
            aria-selected="false"
          >
            Iceland
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionIN"
            value="IN"
            aria-selected="false"
          >
            India
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionID"
            value="ID"
            aria-selected="false"
          >
            Indonesia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionIR"
            value="IR"
            aria-selected="false"
          >
            Iran, Islamic Republic of
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionIQ"
            value="IQ"
            aria-selected="false"
          >
            Iraq
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionIE"
            value="IE"
            aria-selected="false"
          >
            Ireland
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionIM"
            value="IM"
            aria-selected="false"
          >
            Isle of Man
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionIL"
            value="IL"
            aria-selected="false"
          >
            Israel
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionIT"
            value="IT"
            aria-selected="false"
          >
            Italy
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionJM"
            value="JM"
            aria-selected="false"
          >
            Jamaica
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionJP"
            value="JP"
            aria-selected="false"
          >
            Japan
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionJE"
            value="JE"
            aria-selected="false"
          >
            Jersey
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionJO"
            value="JO"
            aria-selected="false"
          >
            Jordan
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionKZ"
            value="KZ"
            aria-selected="false"
          >
            Kazakhstan
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionKE"
            value="KE"
            aria-selected="false"
          >
            Kenya
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionKI"
            value="KI"
            aria-selected="false"
          >
            Kiribati
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionKP"
            value="KP"
            aria-selected="false"
          >
            Korea, Democratic People's Republic of
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionKR"
            value="KR"
            aria-selected="false"
          >
            Korea, Republic of
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionKW"
            value="KW"
            aria-selected="false"
          >
            Kuwait
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionKG"
            value="KG"
            aria-selected="false"
          >
            Kyrgyzstan
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionLA"
            value="LA"
            aria-selected="false"
          >
            Lao People's Democratic Republic
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionLV"
            value="LV"
            aria-selected="false"
          >
            Latvia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionLB"
            value="LB"
            aria-selected="false"
          >
            Lebanon
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionLS"
            value="LS"
            aria-selected="false"
          >
            Lesotho
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionLR"
            value="LR"
            aria-selected="false"
          >
            Liberia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionLY"
            value="LY"
            aria-selected="false"
          >
            Libyan Arab Jamahiriya
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionLI"
            value="LI"
            aria-selected="false"
          >
            Liechtenstein
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionLT"
            value="LT"
            aria-selected="false"
          >
            Lithuania
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionLU"
            value="LU"
            aria-selected="false"
          >
            Luxembourg
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMO"
            value="MO"
            aria-selected="false"
          >
            Macao
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMK"
            value="MK"
            aria-selected="false"
          >
            Macedonia, The Former Yugoslav Republic of
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMG"
            value="MG"
            aria-selected="false"
          >
            Madagascar
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMW"
            value="MW"
            aria-selected="false"
          >
            Malawi
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMY"
            value="MY"
            aria-selected="false"
          >
            Malaysia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMV"
            value="MV"
            aria-selected="false"
          >
            Maldives
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionML"
            value="ML"
            aria-selected="false"
          >
            Mali
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMT"
            value="MT"
            aria-selected="false"
          >
            Malta
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMH"
            value="MH"
            aria-selected="false"
          >
            Marshall Islands
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMQ"
            value="MQ"
            aria-selected="false"
          >
            Martinique
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMR"
            value="MR"
            aria-selected="false"
          >
            Mauritania
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMU"
            value="MU"
            aria-selected="false"
          >
            Mauritius
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionYT"
            value="YT"
            aria-selected="false"
          >
            Mayotte
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMX"
            value="MX"
            aria-selected="false"
          >
            Mexico
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionFM"
            value="FM"
            aria-selected="false"
          >
            Micronesia, Federated States of
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMD"
            value="MD"
            aria-selected="false"
          >
            Moldova, Republic of
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMC"
            value="MC"
            aria-selected="false"
          >
            Monaco
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMN"
            value="MN"
            aria-selected="false"
          >
            Mongolia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionME"
            value="ME"
            aria-selected="false"
          >
            Montenegro
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMS"
            value="MS"
            aria-selected="false"
          >
            Montserrat
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMA"
            value="MA"
            aria-selected="false"
          >
            Morocco
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMZ"
            value="MZ"
            aria-selected="false"
          >
            Mozambique
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMM"
            value="MM"
            aria-selected="false"
          >
            Myanmar
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionNA"
            value="NA"
            aria-selected="false"
          >
            Namibia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionNR"
            value="NR"
            aria-selected="false"
          >
            Nauru
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionNP"
            value="NP"
            aria-selected="false"
          >
            Nepal
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionNL"
            value="NL"
            aria-selected="false"
          >
            Netherlands
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAN"
            value="AN"
            aria-selected="false"
          >
            Netherlands Antilles
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionNC"
            value="NC"
            aria-selected="false"
          >
            New Caledonia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionNZ"
            value="NZ"
            aria-selected="false"
          >
            New Zealand
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionNI"
            value="NI"
            aria-selected="false"
          >
            Nicaragua
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionNE"
            value="NE"
            aria-selected="false"
          >
            Niger
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionNG"
            value="NG"
            aria-selected="false"
          >
            Nigeria
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionNU"
            value="NU"
            aria-selected="false"
          >
            Niue
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionNF"
            value="NF"
            aria-selected="false"
          >
            Norfolk Island
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMP"
            value="MP"
            aria-selected="false"
          >
            Northern Mariana Islands
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionNO"
            value="NO"
            aria-selected="false"
          >
            Norway
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionOM"
            value="OM"
            aria-selected="false"
          >
            Oman
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPK"
            value="PK"
            aria-selected="false"
          >
            Pakistan
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPW"
            value="PW"
            aria-selected="false"
          >
            Palau
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPS"
            value="PS"
            aria-selected="false"
          >
            Palestinian Territory, Occupied
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPA"
            value="PA"
            aria-selected="false"
          >
            Panama
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPG"
            value="PG"
            aria-selected="false"
          >
            Papua New Guinea
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPY"
            value="PY"
            aria-selected="false"
          >
            Paraguay
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPE"
            value="PE"
            aria-selected="false"
          >
            Peru
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPH"
            value="PH"
            aria-selected="false"
          >
            Philippines
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPN"
            value="PN"
            aria-selected="false"
          >
            Pitcairn
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPL"
            value="PL"
            aria-selected="false"
          >
            Poland
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPT"
            value="PT"
            aria-selected="false"
          >
            Portugal
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPR"
            value="PR"
            aria-selected="false"
          >
            Puerto Rico
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionQA"
            value="QA"
            aria-selected="false"
          >
            Qatar
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionRE"
            value="RE"
            aria-selected="false"
          >
            Réunion
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionRO"
            value="RO"
            aria-selected="false"
          >
            Romania
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionRU"
            value="RU"
            aria-selected="false"
          >
            Russia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionRW"
            value="RW"
            aria-selected="false"
          >
            Rwanda
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionBL"
            value="BL"
            aria-selected="false"
          >
            Saint Barthélemy
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSH"
            value="SH"
            aria-selected="false"
          >
            Saint Helena, Ascension and Tristan Da Cunha
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionKN"
            value="KN"
            aria-selected="false"
          >
            Saint Kitts and Nevis
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionLC"
            value="LC"
            aria-selected="false"
          >
            Saint Lucia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionMF"
            value="MF"
            aria-selected="false"
          >
            Saint Martin
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionPM"
            value="PM"
            aria-selected="false"
          >
            Saint Pierre and Miquelon
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionVC"
            value="VC"
            aria-selected="false"
          >
            Saint Vincent and the Grenadines
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionWS"
            value="WS"
            aria-selected="false"
          >
            Samoa
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSM"
            value="SM"
            aria-selected="false"
          >
            San Marino
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionST"
            value="ST"
            aria-selected="false"
          >
            Sao Tome and Principe
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSA"
            value="SA"
            aria-selected="false"
          >
            Saudi Arabia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSN"
            value="SN"
            aria-selected="false"
          >
            Senegal
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionRS"
            value="RS"
            aria-selected="false"
          >
            Serbia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSC"
            value="SC"
            aria-selected="false"
          >
            Seychelles
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSL"
            value="SL"
            aria-selected="false"
          >
            Sierra Leone
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSG"
            value="SG"
            aria-selected="false"
          >
            Singapore
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSK"
            value="SK"
            aria-selected="false"
          >
            Slovakia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSI"
            value="SI"
            aria-selected="false"
          >
            Slovenia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSB"
            value="SB"
            aria-selected="false"
          >
            Solomon Islands
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSO"
            value="SO"
            aria-selected="false"
          >
            Somalia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionZA"
            value="ZA"
            aria-selected="false"
          >
            South Africa
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGS"
            value="GS"
            aria-selected="false"
          >
            South Georgia and the South Sandwich Islands
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionES"
            value="ES"
            aria-selected="false"
          >
            Spain
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionLK"
            value="LK"
            aria-selected="false"
          >
            Sri Lanka
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSD"
            value="SD"
            aria-selected="false"
          >
            Sudan
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSR"
            value="SR"
            aria-selected="false"
          >
            Suriname
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSJ"
            value="SJ"
            aria-selected="false"
          >
            Svalbard and Jan Mayen
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSZ"
            value="SZ"
            aria-selected="false"
          >
            Swaziland
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSE"
            value="SE"
            aria-selected="false"
          >
            Sweden
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionCH"
            value="CH"
            aria-selected="false"
          >
            Switzerland
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionSY"
            value="SY"
            aria-selected="false"
          >
            Syrian Arab Republic
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTW"
            value="TW"
            aria-selected="false"
          >
            Taiwan, Province of China
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTJ"
            value="TJ"
            aria-selected="false"
          >
            Tajikistan
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTZ"
            value="TZ"
            aria-selected="false"
          >
            Tanzania, United Republic of
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTH"
            value="TH"
            aria-selected="false"
          >
            Thailand
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTL"
            value="TL"
            aria-selected="false"
          >
            Timor-Leste
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTG"
            value="TG"
            aria-selected="false"
          >
            Togo
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTK"
            value="TK"
            aria-selected="false"
          >
            Tokelau
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTO"
            value="TO"
            aria-selected="false"
          >
            Tonga
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTT"
            value="TT"
            aria-selected="false"
          >
            Trinidad and Tobago
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTN"
            value="TN"
            aria-selected="false"
          >
            Tunisia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTR"
            value="TR"
            aria-selected="false"
          >
            Turkey
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTM"
            value="TM"
            aria-selected="false"
          >
            Turkmenistan
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTC"
            value="TC"
            aria-selected="false"
          >
            Turks and Caicos Islands
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionTV"
            value="TV"
            aria-selected="false"
          >
            Tuvalu
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionUG"
            value="UG"
            aria-selected="false"
          >
            Uganda
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionUA"
            value="UA"
            aria-selected="false"
          >
            Ukraine
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionAE"
            value="AE"
            aria-selected="false"
          >
            United Arab Emirates
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionGB"
            value="GB"
            aria-selected="false"
          >
            United Kingdom
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionUS"
            value="US"
            aria-selected="true"
          >
            United States
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionUY"
            value="UY"
            aria-selected="false"
          >
            Uruguay
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionUZ"
            value="UZ"
            aria-selected="false"
          >
            Uzbekistan
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionVU"
            value="VU"
            aria-selected="false"
          >
            Vanuatu
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionVE"
            value="VE"
            aria-selected="false"
          >
            Venezuela, Bolivarian Republic of
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionVN"
            value="VN"
            aria-selected="false"
          >
            Vietnam
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionVG"
            value="VG"
            aria-selected="false"
          >
            Virgin Islands, British
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionVI"
            value="VI"
            aria-selected="false"
          >
            Virgin Islands, U.S.
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionWF"
            value="WF"
            aria-selected="false"
          >
            Wallis and Futuna
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionYE"
            value="YE"
            aria-selected="false"
          >
            Yemen
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionZM"
            value="ZM"
            aria-selected="false"
          >
            Zambia
          </option>
          <option
            data-testid="travelers.SKH-1-EXT.countryCode-optionZW"
            value="ZW"
            aria-selected="false"
          >
            Zimbabwe
          </option>
        </optgroup>
      </select>


  )}


  
export default Nationality_selectBox;
